[2025-07-09T05:16:07.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:16:07.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:16:07.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:16:07.254+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2025-07-09T05:16:07.283+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:16:07.292+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'load_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpo4_951pe']
[2025-07-09T05:16:07.296+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask load_task
[2025-07-09T05:16:07.298+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=349) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:16:07.299+0000] {standard_task_runner.py:63} INFO - Started process 350 to run task
[2025-07-09T05:16:07.434+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:16:07.659+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:16:07.661+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:16:08.278+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into MySQL
[2025-07-09T05:16:08.279+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:16:08.279+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:16:08.309+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=load_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T051607, end_date=20250709T051608
[2025-07-09T05:16:08.359+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:16:08.396+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:16:08.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
