[2025-07-09T05:08:01.450+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:08:01.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:08:01.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:08:01.525+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-09T05:08:01.553+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:08:01.562+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'load_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpgi7hly_1']
[2025-07-09T05:08:01.565+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask load_task
[2025-07-09T05:08:01.565+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:08:01.567+0000] {standard_task_runner.py:63} INFO - Started process 258 to run task
[2025-07-09T05:08:01.705+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:08:01.904+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:08:01.906+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:08:02.174+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into MySQL
[2025-07-09T05:08:02.176+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:08:02.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:08:02.200+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=load_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T050801, end_date=20250709T050802
[2025-07-09T05:08:02.265+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:08:02.309+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:08:02.313+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
