[2025-07-09T05:03:28.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:03:28.290+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:03:28.309+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:03:28.310+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-09T05:03:28.342+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:03:28.356+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'load_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp3xilq8_k']
[2025-07-09T05:03:28.360+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:03:28.360+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask load_task
[2025-07-09T05:03:28.361+0000] {standard_task_runner.py:63} INFO - Started process 210 to run task
[2025-07-09T05:03:28.505+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:03:28.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:03:28.782+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:03:29.167+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into MySQL
[2025-07-09T05:03:29.169+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:03:29.170+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:03:29.203+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=load_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T050328, end_date=20250709T050329
[2025-07-09T05:03:29.258+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:03:29.304+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:03:29.312+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
