[2025-07-09T05:17:12.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:17:13.048+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:17:13.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:17:13.071+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2025-07-09T05:17:13.102+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:17:13.109+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'load_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp2jv93_ss']
[2025-07-09T05:17:13.112+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask load_task
[2025-07-09T05:17:13.113+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=367) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:17:13.115+0000] {standard_task_runner.py:63} INFO - Started process 368 to run task
[2025-07-09T05:17:13.243+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.load_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:17:13.437+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:17:13.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:17:13.774+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into MySQL
[2025-07-09T05:17:13.775+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:17:13.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:17:13.799+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=load_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T051713, end_date=20250709T051713
[2025-07-09T05:17:13.893+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:17:13.953+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:17:13.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
